services:

  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: onlineorder
      POSTGRES_PASSWORD: secret
    volumes:
      - onlineorder-pg-local:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

volumes:
  onlineorder-pg-local:
